/*
	Configuration options used by platform specific code.

	Generated by Mini vMac's setup tool
	(`-t lx64 -m Plus -mem 4M -sound 0 -api sdl`), then edited for
	afterglow's headless glue (mac/afterglow_mac.c): no SDL, no window,
	no control mode, 1x speed until the glue sets otherwise.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define RomFileName "vMac.ROM"
#define kCheckSumRom_Size 0x00020000
#define kRomCheckSum1 0x4D1EEEE1
#define kRomCheckSum2 0x4D1EEAE1
#define kRomCheckSum3 0x4D1F8172
#define RomStartCheckSum 1
#define EnableDragDrop 0
#define SaveDialogEnable 0
#define EnableAltKeysMode 0
#define MKC_UnMappedKey  MKC_Control
#define VarFullScreen 0
#define WantInitFullScreen 0
#define MayFullScreen 0
#define MayNotFullScreen 1
#define WantInitMagnify 0
#define EnableMagnify 0
#define MyWindowScale 1
#define WantInitRunInBackground 1
#define WantInitNotAutoSlow 0
#define WantInitSpeedValue 0
#define WantEnblCtrlInt 0
#define WantEnblCtrlRst 0
#define WantEnblCtrlKtg 0
#define NeedRequestInsertDisk 0
#define NeedDoMoreCommandsMsg 0
#define NeedDoAboutMsg 0
#define UseControlKeys 0
#define UseActvCode 0
#define EnableDemoMsg 0
#define NeedIntlChars 0
#define kStrAppName "Mini vMac"
#define kAppVariationStr "minivmac-36.04-afterglow"
#define kStrCopyrightYear "2018"
#define kMaintainerName "unknown"
#define kStrHomePage "(unknown)"
#define kBldOpts "-br 36 -m Plus -mem 4M -sound 0"
